name: Tianqu Docker Image Bulid
on:
#github页面手动触发
  workflow_dispatch: 
#打tag触发，必须是v开头的
  push:
    tags:
      - "v*.*"
env:
  IMAGE_NAME: kube-state-metrics
  DOCKER_REGISTRY: registry.cn-hangzhou.aliyuncs.com/tianqu/kube-state-metric
jobs:

  build-image:

    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    outputs:
      tags: ${{ steps.output-id.outputs.v }}
    steps:
    - uses: actions/checkout@v3
    - id: output-id
      run: |
        VERSION=edge
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        fi
        echo "v=${VERSION}" >> $GITHUB_OUTPUT
    - name: Login Docker Hub
      uses: docker/login-action@v1
      with:
        #这里引用的变量为上一步配置的变量
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PWD }}
    - name: Build the Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: |
          linux/amd64
          linux/arm64
          #推送到镜像仓库  
          push: true
          # 这里会构建两个版本镜像，
          # 1.dweizhao/backend:latest
          # 2.  output-id步骤中获取的v，构建dweizhao/backend:edge或者dweizhao/backend:对应tag值
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.output-id.outputs.v }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
